project:
  type: website
  output-dir: docs

website:
  title: "Menu"
  page-footer:
    left: "Blog made with [Quarto](https://quarto.org/), by Clément Rieux. License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right:
      - icon: github
        href: https://github.com/clementrx
      - icon: linkedin
        href: https://www.linkedin.com/in/ClementRieux/
      - icon: envelope
        href: mailto:clement.rieux@yahoo.com
  navbar:
    right:
      - about.qmd
      - text: Posts
        menu:
          - text: All posts
            href: posts/index.qmd
          - text: English
            href: posts/en.qmd
          - text: Français
            href: posts/fr.qmd
          - text: Español
            href: posts/es.qmd
      - icon: github
        href: https://github.com/clementrx
      - icon: linkedin
        href: https://www.linkedin.com/in/ClementRieux/
      - icon: envelope
        href: mailto:clement.rieux@yahoo.com
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

