project:
  type: website

website:
  title: "Menu"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://www.linkedin.com/in/ClementRieux/
      - icon: envelope
        href: mailto:clement.rieux@yahoo.com
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

